#!/usr/bin/env python3
"""
tools/gen_natives_full.py — generate client/src/natives_full.h from a checkout
of the citizenfx/natives repository (https://github.com/citizenfx/natives).

Every native's 64-bit hash is factual game data (RAGE script native hashes);
the generated header lets the GTA V client call ANY native dynamically through
its runtime-discovered native table (indexed by (hash>>8)&0xFF, hash&0xFF),
and lets client Lua scripts call natives by name.

Usage:  python3 tools/gen_natives_full.py /path/to/citizenfx-natives-checkout
"""
import os
import re
import sys

HASH_RE = re.compile(r"//\s*(0x[0-9A-Fa-f]{8,16})")

def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "/tmp/natives-repo"
    entries = {}  # name -> hash
    for dirpath, _dirs, files in os.walk(root):
        for fn in files:
            if not fn.endswith(".md"):
                continue
            path = os.path.join(dirpath, fn)
            try:
                text = open(path, encoding="utf-8", errors="replace").read()
            except OSError:
                continue
            name = None
            for line in text.splitlines():
                if line.startswith("## "):
                    parts = line[3:].strip().split()
                    if not parts:
                        continue
                    cand = parts[0].upper()
                    if cand.startswith("_0X") or cand.startswith("0X"):
                        name = None
                        break
                    name = cand
                    break
            if not name:
                continue
            m = HASH_RE.search(text)
            if not m:
                continue
            h = int(m.group(1), 16)
            if h == 0 or h in (0x00000000, 0xFFFFFFFF):
                continue
            entries.setdefault(name, h)

    items = sorted(entries.items(), key=lambda kv: kv[0].lower())
    out = [
        "// natives_full.h — GENERATED by tools/gen_natives_full.py from",
        "// the citizenfx/natives repository (https://github.com/citizenfx/natives).",
        "// Native hashes are factual game data; all other code in the client is original.",
        "// Every native below can be called through the runtime-discovered native table:",
        "//   slot(hash) = tbl[(hash >> 8) & 0xFF][hash & 0xFF]",
        "#pragma once",
        "#include <cstdint>",
        "#include <cstring>",
        "",
        "struct NativeDef {",
        "    const char* name;",
        "    uint64_t hash;",
        "};",
        "",
        f"static const NativeDef NATIVES[] = {{",
    ]
    for name, h in items:
        out.append(f'    {{"{name}", 0x{h:016X}ULL}},')
    out += [
        "};",
        "",
        f"static const size_t NATIVES_COUNT = {len(items)};",
        "",
        "// case-insensitive binary search over the name-sorted table",
        "inline uint64_t nativeHashByName(const char* name) {",
        "    if (!name || !*name) return 0;",
        "    size_t lo = 0, hi = NATIVES_COUNT;",
        "    while (lo < hi) {",
        "        size_t mid = (lo + hi) / 2;",
        "#ifdef _WIN32",
        "        int c = _stricmp(name, NATIVES[mid].name);",
        "#else",
        "        int c = strcasecmp(name, NATIVES[mid].name);",
        "#endif",
        "        if (c == 0) return NATIVES[mid].hash;",
        "        if (c < 0) hi = mid; else lo = mid + 1;",
        "    }",
        "    return 0;",
        "}",
        "",
    ]
    dest = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "client", "src", "natives_full.h")
    dest = os.path.normpath(dest)
    with open(dest, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {dest}: {len(items)} natives")

if __name__ == "__main__":
    main()
